<?php

return [
    "OPENAI_API_KEY" => env('OPENAI_API_KEY'),
    "PYTHON_SCRIPT_PATH" => env('PYTHON_SCRIPT_PATH'),
    "PYTHON_SCRIPT_PATH2" => env('PYTHON_SCRIPT_PATH2'),
    "PYTHON_SCRIPT_PATH3" => env('PYTHON_SCRIPT_PATH3'),
    "PYTHON_SCRIPT_PATH4" => env('PYTHON_SCRIPT_PATH4'),
    "REPLICATE_API_TOKEN" => env('REPLICATE_API_TOKEN'),
    "LLAMA_PYTHON_SCRIPT_PATH" => env('LLAMA_PYTHON_SCRIPT_PATH'),
    "LLAMA_API_KEY" => env('LLAMA_API_KEY'),
    "PERFORMANCE_PYTHON_SCRIPT_PATH" => env('PERFORMANCE_PYTHON_SCRIPT_PATH'),
];